version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/data/postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@urly.dev
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - 5050:80
    restart: unless-stopped

  urly-web-api:
    image: urly-web-api
    build:
      context: .
      dockerfile: Dockerfile
    container_name: urly-web-api
    ports:
      - 5002:80
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres:
  pgadmin:
